### ISSUE TITLE
Github doesn't have DM's

### ISSUE THREAD

**Issue by rpasta42** [MoochMcGee/PCem-mooch#8]
Hey dude,

You probably don't remember me, but we worked on emulator together few years ago: https://github.com/KostyaKow/IBM5150

I wanted to get in touch to say hi and see what you're working on. I lost your contact info and i don't want to post my skype/email on github issues, so maybe we can do it through PGP or something?

**Comment by bachimusprime** [comment]
@KostyaKow I actually do remember, you, my friend! Here's an email I use to filter out some of the crazies from my normal inbox. It should be safe for me to post this on here. mooch@firemail.cc
